[gcp_service_account]
type = "service_account"
project_id = "vernal-zone-459807-k5"
private_key_id = "ccd7fb2162b983c952b93908b13db5e7d85b911f"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCgr1HwTbmNS5lB
SXCZU45Ilvqa+r8BHvRhz5hdbDJMVwEjFwu6r1nfQoF9i3RKf6PZZKNi1zzwVV2X
G4sLaCjEI2WSLxj1xeI3G2XyQCwmlI0PfjxMCrRFYGwnOOD3Txktwc6xdGAo30Nv
SO7OeGojkG4d/zutVwe/aSm+zdR3rGKekLba3EItEleLLtCKCBagufwVM9euPrvk
tnJgY9L0dV0NGY2bCElKOq+2u3B8qA8ug/P7ZbY0ugN93hL5XpYRKlsfNI4WbdNb
iIKlRMQhdnLe7yZzquSUZq6tpgxsO9FFwPpJIDOGUrXYeuy3Qg6gRi1jS1bPeppf
SEQTCs/7AgMBAAECggEAO087EVW/DXZABScUVqPOuuBvc9Dlu4YvcgLsHF+ZWTAs
DUWuYKPkqlGj9jEJJY5jbhSFcjA8IAGCYAockoNJuMvP69tSfTUjQG/uezJQmZTv
VC6mFvNEgu8KPJf0AZTCmG8W2c04yR1PiL4E11T+6E2hN5VD88FR7MbmT7UtnVX/
RtPTH6YzyEHemM8jqNpOB95hWkbSaxZ+4D7GMibWx9tQ/m1rJPZc2xchuYltTlhq
L7uzAcFOOu3dT0pJmLKVl2r0L4TZ6u3OriegKsC8srhjZnfENacE9HbNdCOH+Xug
UBc6pI9evQtCr9pWWKPCAGwNY/LJ0hnm/kgXGr8oMQKBgQDftsn2WeievzMJJfi4
OFdOIq8S8jjIw4rPzvdIrwseuTjQm6bGjWyUhOarPC1MEIbhO4gzbGjVhoq4bCDN
nwsCdn/kmbXOLg0dzTMR3a16WT2tV5MhTyuYCsb4us9vFBa+99o6k0+2CFFFZ8r7
b68hSMIsYaGeMqT/NifxMB/BnQKBgQC33+QcAkgd8/YM5ro6Wo80dQWK9pK0I0Tt
5bmtH1WE8JAJ381kiys2RM9MqwipeQsuwHurlstvQCSUsVrMYUnAqoNlKRh2IEz3
Nm3XXbs7xq+zZtuOz5aeApa8wQZdCC9L9n3X8n8dgEU3AXNHf6QV9QJzQmLReRad
opXM4IYQdwKBgHbOJ+tATB0iBQRyued7ZEIGgVtab3WPAwThMMnUy98BFn8Sajs/
l8431hhR2OxwSnEKoIZOqE3dKYZPRgxszff83maUisx4AFc3RkvSofI7ull4DJa/
6LLR5mDpNIgU7w9zqN06pjZRrHdja5Sj9ymB7jyLjLzqwF0YcZXQrMyxAoGBAJ0x
V5amULbiqFfRLCXU45ZJ8IojT7mWaUgj239oSTkUW19FqBarby6+1qXJleckJu45
+b/wc0xRfrRrhp8xENcYLqpd3p6l8IZrTq4OYJGywuRRK6RETZQZzHnjXqhL5fs/
58ekdQ1oakOjBsV6FnH6+rREbax8o1vx8bSrwZDzAoGAEJavw0JT3Ft3LUHheEz/
OYUF6rIkh+RiOEQgd+k671qANoDM/kKXa5wS6evZNi2QuGsNhZCLBq88UzYQSZT5
mxKxsaA7gyYboUaUPrB/YOtcgaEoIqm6y4jE+FxfjL1GhL3jLAwBaUuIsQL1eB/x
8oit9Yuije6kuRffy8DYijw=
-----END PRIVATE KEY-----"""
client_email = "nuvedo-scheduler@vernal-zone-459807-k5.iam.gserviceaccount.com"
client_id = "110756322906967023647"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/nuvedo-scheduler%40vernal-zone-459807-k5.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
